# code: language=ansible
---
- name: Install dependencies (apt)
  become: true
  ansible.builtin.apt:
    name: "{{ vscode_packages }}"
    state: present

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: Install key (apt)
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: true

- name: Install VS Code repo (apt)
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Install VS Code (apt)
  become: true
  ansible.builtin.apt:
    name: "code"
    state: present
